version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Requirements to run style checks and build documentation
  - package-ecosystem: "pip"
    directories:
     - "/.github/workflows/requirements/style/*"
     - "/lib/spack/docs"
    schedule:
      interval: "daily"
